### ISSUE TITLE
How can I add new pages and link to them?

### ISSUE THREAD

**Issue by klauso** [ps-mr/website#24]
For instance, I'd like to add a page in /team/ostermann and link to it.
I've added a .md file, but nothing seems to happen with it (i.e., no HTML generation).

How do I do it?

**Comment by Toxaris** [comment]
Create a file `/team/ostermann/foo.md` and add an empty YAML frontmatter:

~~~
---
---

Text of page here.
~~~

Because of the YAML frontmatter (the part with the `---` markers), Jekyll should pick up the file and transform it to HTML, using a default configuration based on the directory you put the file in. You can also put `key = value` pairs between the  `---` markers to configure things more.

**Comment by Blaisorblade** [comment]
@yfcai just asked the same question for his paper website. What tricked him is the another pitfall (already addressed by your answer):
- he expected http://ps.informatik.uni-tuebingen.de/research/functors.html to appear
- he should have gone to http://ps.informatik.uni-tuebingen.de/research/functors/ instead.

**Comment by Blaisorblade** [comment]
The open issue is in #25, so closing.
